import Link from 'next/link';
import '../styles/globals.css';
import Image from 'next/image';

import GithubIcon from '../public/github.svg';
import LinkedInIcon from '../public/linkedin.svg';

export const metadata = {
  title: `Shakib's blog`,
  description: 'Generated by create next app',
};

const NavLink = ({ href, children }: { href: string; children: React.ReactNode }) => {
  return (
    <Link href={href} className={`text-md font-medium text-slate-500 hover:text-slate-900`}>
      {children}
    </Link>
  );
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const header = (
    <header className="flex items-center justify-between py-3 border-b border-slate-700">
      <div className="flex items-center space-x-4">
        <Link href="/">
          <h1 className="text-lg text-slate-600 font-medium hover:text-slate-900">Shakib Ahmed</h1>
        </Link>
      </div>
      <div className="flex items-center space-x-6">
        <NavLink href="/">Posts</NavLink>
        <NavLink href="/about">About</NavLink>
      </div>
    </header>
  );

  const footer = (
    <footer>
      <div className="border-t border-slate-700 py-4 text-center text-slate-400">
        <div className="flex justify-center gap-3">
          <a
            href="https://github.com/shakib1729"
            target="_blank"
            rel="noopener noreferrer"
            className="opacity-75 hover:opacity-100"
          >
            <Image src={GithubIcon} width={30} alt="Github Icon" />
          </a>
          <a
            href="https://www.linkedin.com/in/shakib-1729/"
            target="_blank"
            rel="noopener noreferrer"
            className="opacity-75 hover:opacity-100"
          >
            <Image src={LinkedInIcon} width={30} alt="LinkedIn Icon" />
          </a>
        </div>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <head />
      <body>
        <div className="mx-auto max-w-2xl px-6">
          {header}
          <div className="pt-4 pb-6">{children}</div>
          {footer}
        </div>
      </body>
    </html>
  );
}
